// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function ExecuteCode(arg1:string):Promise<main.ExecuteResult>;

export function GetClipboard():Promise<string>;
