// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function ExecuteCode(arg1) {
  return window['go']['main']['App']['ExecuteCode'](arg1);
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}
